### ISSUE TITLE
this.$msal.isAuthenticated() is not available, 

### ISSUE THREAD

**Issue by antonio-castellon** [ahermant/vue-msal-browser#3]
this.$msal.isAuthenticated() is not available, doesnt fit with your guideline

**Comment by ahermant** [comment]
Hi Antonio, 
Thanks for your feedback.
Are you using the plugin with Vue 2 or Vue 3 ?
Did you have an error during the initialization step (https://github.com/ahermant/vue-msal-browser#initialize-the-plugin) ?

**Comment by ahermant** [comment]
Indeed `isAuthenticated()` was not available. I have suggested another option in the documentation. Thanks !

**Comment by antonio-castellon** [comment]
Many thanks for that
